export const TRIGGER_CONNECT = 'TRIGGER_CONNECT'
export const CONNECTED_SUCCESS = 'CONNECTED_SUCCESS'
export const DISCONNECTED_SUCCESS = 'DISCONNECTED_SUCCESS'
export const META_MASK_ADDRESS = 'META_MASK_ADDRESS'

